config/routes.rb
Cardiffcollective::Application.routes.draw do

  resources :tags, :only => [:index, :show] do
    collection do
      get 'all'
    end
  end

  match '/me' => 'users#me', :as => :my_profile, :via => :get
  match '/:id' => 'users#show', :as => :user, :via => :get

  devise_for :users
  resources :users, :only => [:index] do
    member do
      post 'contact'
    end
  end

  root :to => "users#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable,
  # :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,
                  :first_name, :last_name, :website, :company, :bio,
                  :twitter, :facebook, :skills, :learning, :skill_list, 
                  :learning_list

  acts_as_taggable
  acts_as_taggable_on :skills, :learning

  before_save :capitalize_names

  validates :first_name, :last_name, :email, :presence => true
  validates :email, :uniqueness => { :case_sensitive => false }
  validates :bio, :length => { :in => 2..140 }

  # Public: The User's full name
  #
  # Returns a String of the User's first_name and last_name
  def name
    "#{ first_name } #{ last_name }"
  end

  alias_method :full_name, :name

  # ===========================================================================
  # Private
  # ===========================================================================

  private

  # Internal: Capitalize each name attribute
  #
  # Example
  #
  #   @user.first_name = 'gareth'
  #   @user.save
  #   @user.first_name
  #   # => "Gareth"
  #
  # Returns a String
  def capitalize_names
    first_name.capitalize!
    last_name.capitalize!
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @skills = User.tag_counts_on(:skills).sort_by(&:count).reverse.take(5)
    @learnings = User.tag_counts_on(:learning).sort_by(&:count).reverse.take(5)
  end

  def all
    @tags = (User.tag_counts_on(:skills) + User.tag_counts_on(:learning)).uniq.sort_by { |tag| tag.taggings.count }.reverse
  end

  def show
    @tag = params[:id]
    @skilled = User.tagged_with(@tag, :on => :skills)
    @learning = User.tagged_with(@tag, :on => :learning)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users_letters = User.all.group_by { |u| u.name.first }.sort
    @learnings = User.tag_counts_on(:learning).sort_by(&:count).reverse.take(5)
  end

  def show
    @user = User.find(params[:id])
  end

  def me
    if current_user
      redirect_to current_user
    else
      redirect_to new_user_registration_path
    end
  end

  def contact
    if current_user
      to = User.find(params[:id])
      from = current_user
      UserMailer.contact_email(from, to, params[:message]).deliver
      redirect_to user_path(to), notice: "Your message to #{ to.name } was sent"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<title>Cardiff Collective</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
	<!--[if IE]>
		<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="wrap">

  	<header id="banner" class="cf">
  	  <div class="logo">
    		<h1 class="mark"><%= link_to 'Cardiff Collective', root_url %></h1>
    		<span class="strapline">Connect with creative people in Cardiff</span>
    	</div>
      <%= render partial: 'devise/menu/login_items' %>
  	</header>

  	<div id="main" class="cf">
  	  <%= render partial: 'shared/flash', object: flash %>

      <%= yield %>
    </div>

    <footer id="footer" class="cf">
    </footer>

  </div>

  <div id="feedback">
    <%= link_to 'Feedback', 'https://trello.com/board/cardiff-collective/505e3f6040376cd93ec5f398', class: 'feedback', target: '_blank' %>
  </div>

  <% if Rails.env.production? %>
    <%= render 'shared/analytics' %>
    <%= render 'shared/fork' %>
  <% end %>

</body>
</html>

app/views/shared/_analytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-36608476-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/shared/_flash.html.erb
<% if flash.present? -%>
  <% flash.each do |name, msg| -%>
    <%= content_tag :div, msg, class: "message message-#{ name }" %>
  <% end -%>
<% end -%>

app/views/shared/_fork.html.erb
<a href="https://github.com/cardiffstart/cardiffcollective">
  <img style="position: absolute; top: 0; right: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_right_darkblue_121621.png" alt="Fork me on GitHub">
</a>

app/views/tags/all.html.erb
<section id="all-tags">
  <h1>People in Cardiff know about</h1>
  <ul class="tags">
    <% @tags.each do |tag| %>
      <li class="cf">
        <%= link_to tag, tag_path(tag), class: 'tag' %>
        <ul class="user-list cf">
          <% User.tagged_with(tag.name).each do |user| %>
            <li class="user"><%= link_to gravatar_image_tag(user.email, alt: user.name, class: 'avatar', gravatar: { size: 32 }), user, title: user.name %></li>
          <% end %>
        </ul>
      </li>
    <% end %>
  </ul>
</section>

app/views/tags/index.html.erb
<article class="tag-index">

  <% if current_user %>
    <section id="learning">
      <h1>You want to learn about</h1>

      <ul class="user-list">
      <% current_user.learning.each do |tag| %>
        <% User.tagged_with(tag, :on => :skills).each do |user| %>
          <li class="user">
            <%= gravatar_image_tag user.email, alt: user.name, class: 'avatar', gravatar: { size: 32 } %>
            <%= link_to user.name, user %> can help you learn <%= link_to tag, tag_path(tag), class: 'tag' %>
          </li>
        <% end %>
      <% end %>
      </ul>
    </section>

    <section id="skills">
      <h1>Help others learn</h1>

      <ul class="user-list">
      <% current_user.skills.each do |tag| %>
        <% User.tagged_with(tag, :on => :learning).each do |user| %>
          <li class="user">
            <%= gravatar_image_tag user.email, alt: user.name, class: 'avatar', gravatar: { size: 32 } %>
            You can help <%= link_to user.name, user %> to learn <%= link_to tag, tag_path(tag), class: 'tag' %>
          </li>
        <% end %>
      <% end %>
      </ul>
    </section>
  <% else %>
    <section id="skills">
      <h1>Most popular skills</h1>
      <ul class="tags">
        <% @skills.each do |tag| %>
          <li><%= link_to tag, tag_path(tag), class: 'tag' %></li>
        <% end %>
      </ul>
    </section>

    <section id="learning">
      <h1>Most requested skills</h1>
      <ul class="tags">
        <% @learnings.each do |tag| %>
          <li><%= link_to tag, tag_path(tag), class: 'tag' %></li>
        <% end %>
      </ul>
    </section>

    <section id="all">
      <%= link_to raw('See all tags &rarr;'), all_tags_path %>
    </section>
  <% end %>

</article>

app/views/tags/show.html.erb
<article class="tag-show">

  <section id="skills">
    <h1><%= pluralize(@skilled.size, 'person knows', 'people know') %> about <span class="tag"><%= @tag %></span></h1>

    <ul class="user-list">
      <% @skilled.each do |user| %>
        <li class="user">
          <%= gravatar_image_tag user.email, alt: user.name, class: 'avatar', gravatar: { size: 32 } %>
          <%= link_to user.name, user_path(user) %>
        </li>
      <% end %>
    </ul>
  </section>

  <section id="learning">
    <h1><%= pluralize(@learning.size, 'person wants', 'people want') %> to learn about <span class="tag"><%= @tag %></span></h1>

    <ul class="user-list">
      <% @learning.each do |user| %>
        <li class="user">
          <%= gravatar_image_tag user.email, alt: user.name, class: 'avatar', gravatar: { size: 32 } %>
          <%= link_to user.name, user_path(user) %>
        </li>
      <% end %>
    </ul>
  </section>

</article>

app/views/users/index.html.erb
<aside id="intro" class="cf">
  <h2>Can you help with&hellip;</h2>
  <ul class="tags">
    <% @learnings.each do |tag| %>
      <li><%= link_to tag, tag_path(tag), class: 'tag' %></li>
    <% end %>
    <li><%= link_to raw('See all tags &rarr;'), all_tags_path, class: 'tag' %></li>
  </ul>

</aside>

<article class="users">
  <h1>People in Cardiff</h1>
  <header>
    <ol class="index cf">
      <% ("A".."Z").each do |letter| %>
        <li><%= link_to letter, "##{ letter.downcase }" %></li>
      <% end %>
    </ol>
  </header>

  <% @users_letters.each do |letter, users| %>
    <h2 id="<%= letter.downcase %>" class="index-letter"><%= letter.upcase %></h2>

    <ol class="user-list cf">
      <% users.each do |user| %>
        <li class="user">
          <%= gravatar_image_tag user.email, alt: user.name, class: 'avatar', gravatar: { size: 80 } %>
          <%= link_to raw("<div>#{ user.first_name }</div><div>#{ user.last_name }</div>"), user_path(user) %>
        </li>
      <% end %>
    </ol>
  <% end %>
</article>

app/views/users/show.html.erb
<article class="user">
  <header>
    <%= gravatar_image_tag @user.email, alt: @user.name, class: 'avatar' %>
    <h1 class="name"><%= @user.name %></h1>
    <%= link_to @user.website, @user.website, class: 'website' %>
    <span class="company"><%= @user.company %></span>
  </header>

  <section id="social-media" class="social-media">
    <p>
    	<%= if @user.twitter.present? %>
    	  <%= link_to image_tag("twitter.jpg", :alt => "Twitter", :id => "twitter_icon", class: "social-icon"  ), "http://twitter.com/" + @user.twitter, class: 'twitter' %>
    	<%= end %>
    	<%= if @user.facebook.present? %>
    	  <%= link_to image_tag("facebook.jpg", :alt => "Facebook", :id => "facebook_icon", class: "social-icon" ), "http://facebook.com/" + @user.facebook, class: 'facebook' %>
    	<%= end %>
    </p>
  </section>

  <section id="bio" class="bio">
    <p><%= @user.bio %></p>
  </section>

  <section id="skills">
    <div class="skills core">
      <h1 class="title">I know a bit about:</h1>
      <ul class="tags">
        <% @user.skills.each do |tag| %>
          <li><%= link_to tag, tag_path(tag), class: 'tag' %></li>
        <% end %>
      </ul>
    </div>

    <div class="skills desired">
      <h1 class="title">I want to know more about:</h1>
      <ul class="tags">
        <% @user.learning.each do |tag| %>
          <li><%= link_to tag, tag_path(tag), class: 'tag' %></li>
        <% end %>
      </ul>
    </div>
  </section>

  <footer class="contact">
    <% if current_user == @user %>
      <%= link_to 'Find people who share your interests', tags_path %>
    <% elsif user_signed_in? %>
      <h1>Contact <%= @user.first_name %></h1>
      <%= form_tag contact_user_path(@user) do %>

        <div class="field">
          <%= text_area_tag :message, '', placeholder: "Your message to #{ @user.first_name }" %>
        </div>

        <div class="field actions">
          <%= submit_tag 'Send Message' %>
        </div>

      <% end %>
    <% else %>
      <h1>Contact <%= @user.first_name %></h1>
      <p><%= link_to 'Sign In', new_user_session_path %> to contact <%= @user.name %>.</p>
    <% end %>
  </footer>
</article>